# Site setings
markdown: redcarpet
highlighter: pygments
baseurl: /screencasterz
exclude: ['README.md','.gitignore']

#Site Information
name: ScreenCasterz
description: This is the official website of the YouTube channel ScreenCasterz.
author: omegadeep10

#Pagination settings
paginate: 5
paginate_path: "/blog/page:num/"
